server
{
    listen 80;
    listen [::]:80;
    server_name 115.159.109.106;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/process/web/dist;

    #ERROR-PAGE-START
    error_page 404 /404.html;
    #ERROR-PAGE-END

    include enable-php-00.conf;

    # API反向代理配置
    location /api {
        proxy_pass http://127.0.0.1:3006;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|ico|svg)$
    {
        expires      30d;
        error_log /dev/null;
        access_log /dev/null;
    }
    
    location ~ .*\.(js|css|woff|woff2|ttf|eot)$
    {
        expires      12h;
        error_log /dev/null;
        access_log /dev/null;
    }

    location /app/ {
        alias /www/wwwroot/process/web/dist/app/;
        index index.html;
        try_files $uri $uri/ /app/index.html;
        autoindex off;
    }
    location /survey/ {
        alias /www/wwwroot/process/web/dist/survey/;
        index index.html;
        try_files $uri $uri/ /survey/index.html;
        autoindex off;
    }
    location /mini/ {
        alias /www/wwwroot/process/web/dist/mini/;
        index index.html;
        try_files $uri $uri/ /mini/index.html;
        autoindex off;
    }
    
    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log  /www/wwwlogs/115.159.109.106.log;
    error_log   /www/wwwlogs/115.159.109.106.error.log;
}
