const express = require('express')
const router = express.Router()
const process_handler = require('../router_handler/process')

router.post('/list', process_handler.list)
router.post('/problemList', process_handler.problemList)
router.post('/create', process_handler.create)
router.post('/update', process_handler.update)
router.post('/delete', process_handler.delete)
router.post('/batchDelete', process_handler.batchDelete)
router.post('/detail', process_handler.detail)
router.post('/updateTechnicianVideo', process_handler.updateTechnicianVideo)
router.post('/updateWebVideo', process_handler.updateWebVideo)
router.post('/updateImage', process_handler.updateImage)
router.post('/updateFactoryTechnicianVideo', process_handler.updateFactoryTechnicianVideo)
router.post('/updateFactoryWebVideo', process_handler.updateFactoryWebVideo)
router.post('/updateFactoryImage', process_handler.updateFactoryImage)
router.post('/updateMiniImage', process_handler.updateMiniImage)
router.post('/updateProgressNote', process_handler.updateProgressNote)
router.post('/updateIntraoralAdjuster', process_handler.updateIntraoralAdjuster)
module.exports = router

